#!/usr/bin/env bash

#set -o errexit

# Path on Android to user files
user_home=/storage/emulated/0
# Path on Android to physical SD card
# user_card=/storage/9C33-6BBD
ssh_host=android # configured in ~/.ssh/config

#######################################
# Move contents of first given directory from Android to second given directory
# on computer.
# Globals:
#   $user_home  (string) Path on Android to user files
# Arguments:
#   $src  (string)  Path on Android to move files from, relative to $user_home
#   $dst  (string)  Path on computer to copy files to
# Returns:
#   None
#######################################
move_folder () {
  local src=$1
  local dst=$2
  ssh $ssh_host test -d "$src" || return 0
  rsync -avz -P --remove-source-files -e ssh "$ssh_host:$src/" "$dst" &&
  ssh $ssh_host find "$src/" -depth -type d -delete
}

#######################################
# Copy to given directory all WhatsApp images and videos newer than a file
# android-transfer-media-timestamp in WhatsApp/Media
# Globals:
#   $user_home  (string) Path on Android to user files
# Arguments:
#   $dst  (string)  Path on computer to copy files to
# Returns:
#   None
#######################################
copy_whatsapp_media () {
  local dst=$1
  local ts=android-transfer-media-timestamp
  local media=$user_home/WhatsApp/Media/
  local t
  local template=android-transfer-media.XXXXXX
  t=$(mktemp -d $template 2>/dev/null || mktemp -d -t $template)
  ssh $ssh_host > "$t/log" << EOF
    cd "$media" &&
    find 'WhatsApp Video' 'WhatsApp Images' 'WhatsApp Animated Gifs' -maxdepth 1 -type f ! -iname '.*' -newer "$media/$ts" -print0
EOF
  if grep 'WhatsApp' "$t/log"; then # if no results, last line is useless
    tail -n1 "$t/log" > "$t/f" # remove shell welcomes like 'Nexus_6P:3.10.73-ge0bfb9b'
    rsync -av -P --files-from="$t/f" --from0 -e ssh "$ssh_host:$media" "$dst" &&
    ssh $ssh_host touch "$media/$ts"
  fi
  rm -rf "$t"
}

main () {
  if (( $# != 1 )); then
    printf "Usage: %s destination\n" "$0" >&2
    exit 1
  fi
  local dest=$1
  if [[ ! -d $dest ]]; then
    printf "Error: Destination not directory or does not exist: %s\n" "$dest">&2
    exit 1
  fi

  move_folder "$user_home/Download" "$dest"
  move_folder "$user_home/DCIM/Camera" "$dest"
  # move_folder "$user_card/DCIM/Camera" "$dest" # Galaxy S8
  move_folder "$user_home/DCIM/Facebook" "$dest"
  move_folder "$user_home/Pictures/Screenshots" "$dest" # Nexus 6P, Essential PH-1
  # move_folder "$user_home/DCIM/Screenshots" "$dest" # Galaxy S8
  # CameraFi, USB camera app
  move_folder "$user_home/DCIM/CameraFi" "$dest"
  move_folder "$user_home/Pictures/Messenger" "$dest"
  move_folder "$user_home/Pictures/LINE" "$dest"
  copy_whatsapp_media "$dest"
}

main "$@"


